service: us-visa-rescheduler

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64
plugins:
  - serverless-offline
functions:
  demo:
    timeout: 300
    memorySize: 2048
    image:
      name: img
    events:
      - schedule:
          rate: rate(3 minutes)
          enabled: true
